import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { OriginalVideoProvider } from "./context/VideoContext";
import { EditedVideoProvider } from "./context/EditedVideoContext";
import { SocialMediaContextProvider } from "./context/SocialMediaContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        {/* Wide-coverage fonts so translated subtitles render correctly */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;600&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;600&display=swap"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SocialMediaContextProvider>
            <OriginalVideoProvider>
                <EditedVideoProvider>{children}</EditedVideoProvider>
            </OriginalVideoProvider>
        </SocialMediaContextProvider>
      </body>
    </html>
  );
}
